server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
    initialSize: 1
    minIdle: 1
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    non-secure-port: 8081
    non-secure-port-enabled: true
    secure-port: 8081
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
